const TIP_DATA = {
  season3: {
    theme: "I'm learning to take care of myself.",
    episodes: [
      {
        number: 1,
        title: "NervousLiy; Stress and the Nervous System",
        description: "What stress is actually doing to your body and organs. The entry point — because everyone's been here.",
        tag: "Biology",
        status: "coming-soon",
        youtubeId: null,
        research: [],
      },
      {
        number: 2,
        title: "MentalLiy; Anxiety and Depression",
        description: "Lived experience, no filter. What it feels like day to day and what actually helps.",
        tag: "Mental Health",
        status: "coming-soon",
        youtubeId: null,
        research: [],
      },
      {
        number: 3,
        title: "CyclicaLiy; The Period Cycle",
        description: "Educational and empowering. Working with your cycle, not against it.",
        tag: "Biology",
        status: "coming-soon",
        youtubeId: null,
        research: [],
      },
      {
        number: 4,
        title: "ConfidentLiy; Finding Self Confidence",
        description: "The messy process of building it — after the inner work has already started.",
        tag: "Lifestyle",
        status: "coming-soon",
        youtubeId: null,
        research: [],
      },
      {
        number: 5,
        title: "PhysicaLiy; Working Out",
        description: "Movement as self care. Ends the season on something actionable and energizing.",
        tag: "Lifestyle",
        status: "coming-soon",
        youtubeId: null,
        research: [],
      },
    ],
  },

  previousEpisodes: [
    { title: "EmotionalLiy; Attachment Styles", youtubeId: "-fE6cG-c4OA", tag: "Lifestyle", season: 2 },
    { title: "HistoricalLiy; It's in Our Genes", youtubeId: "8nbvJ6JfxJI", tag: "Biology", season: 2 },
    { title: "FinancialLiy; Self Care or OverSpending? Between Treating Yourself and Staying Financially Healthy", youtubeId: "N8Bljt9PXPs", tag: "Lifestyle", season: 2 },
  ],

  resources: [
    {
      type: "Book",
      title: "My Grandmother's Hands",
      author: "Resmaa Menakem",
      description: "Racialized trauma and the pathway to mending our hearts and bodies — trauma healing that lives in the body, not just the mind.",
      url: "https://resmaa.com/about-resmaa-menakem/",
      relatedEpisode: 1,
    },
    {
      type: "Book",
      title: "From Fibroids to Freedom",
      author: "Tanika Gray Valbrun",
      description: "The White Dress Project founder on fibroids, heavy and painful periods, and reclaiming your cycle.",
      url: "https://www.sheldonpress.co.uk/titles/tanika-gray-valbrun/from-fibroids-to-freedom/9781399817301/",
      relatedEpisode: 3,
    },
    {
      type: "Book",
      title: "The Unapologetic Guide to Black Mental Health",
      author: "Dr. Rheeda Walker",
      description: "Navigating an unequal system, spotting the signs, and building real tools for emotional wellness.",
      url: "https://www.newharbinger.com/9781684034147/the-unapologetic-guide-to-black-mental-health/",
      relatedEpisode: 2,
    },
    {
      type: "Book",
      title: "Sisters of the Yam",
      author: "bell hooks",
      description: "Black women and self-recovery — how self-care and collective healing are also political acts.",
      url: "https://www.routledge.com/Sisters-of-the-Yam-Black-Women-and-Self-Recovery/hooks/p/book/9781138821682",
      relatedEpisode: 4,
    },
    {
      type: "Book",
      title: "All About Love",
      author: "bell hooks",
      description: "New visions for what love actually requires — care, commitment, and accountability, not just feeling.",
      url: "https://www.harpercollins.ca/9780060959470/all-about-love/",
      relatedEpisode: null,
    },
    {
      type: "Book",
      title: "What Happened to You?",
      author: "Oprah Winfrey & Dr. Bruce Perry",
      description: "Conversations on trauma, resilience, and healing — reframing 'what's wrong with you' as 'what happened to you.'",
      url: "https://www.panmacmillan.com/authors/oprah-winfrey/what-happened-to-you/9781529068467",
      relatedEpisode: null,
    },
    {
      type: "Book",
      title: "Rest Is Resistance",
      author: "Tricia Hersey",
      description: "The Nap Ministry founder's manifesto on rest as reclamation — not a reward you earn after burning out.",
      url: "https://www.hachettebookgroup.com/titles/tricia-hersey/rest-is-resistance/9780316365536/",
      relatedEpisode: 5,
    },
    {
      type: "Book",
      title: "The Body Keeps the Score",
      author: "Bessel van der Kolk",
      description: "How trauma reshapes the body and brain.",
      url: "https://www.besselvanderkolk.com/resources/the-body-keeps-the-score",
      relatedEpisode: null,
    },
  ],
};
